apiVersion: batch/v1
kind: Job
metadata:
  name: build-breizhsport-application
  namespace: cube-3
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
      - name: docker-build
        image: "docker:{{ .Values.docker.version }}"
        env:
        - name: SSH_KEY
          valueFrom:
            secretKeyRef:
              name: application-secret
              key: SSH_KEY
        command: ["sh", "-c"]
        args:
        - |
          mkdir -p ~/.ssh &&
          echo "$SSH_KEY" > ~/.ssh/id_rsa &&
          chmod 600 ~/.ssh/id_rsa &&
          eval $(ssh-agent -s) &&
          ssh-add ~/.ssh/id_rsa &&
          ssh-keyscan github.com >> ~/.ssh/known_hosts &&
          apk add --no-cache git &&

          git clone -b {{ .Values.application.branch }} {{ .Values.application.githubLink }} /app/breizhsport &&
          cd /app/breizhsport &&
          rm docker-compose.yml &&

          docker image prune -a -f &&

          docker system prune -a --volumes -f &&

          docker build -t breizhsport:production . &&

          echo "Build completed"
        volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
      restartPolicy: Never
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
          type: Socket
