apiVersion: batch/v1
kind: Job
metadata:
  name: build-breizhsport-application
  namespace: cube-3
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'sshkey'
        vault.hashicorp.com/agent-inject-secret-config: 'secret/breizhsport/sshkey'
        # Environment variable export template
        vault.hashicorp.com/agent-inject-template-config: |
          {{`{{- with secret "secret/breizhsport/sshkey" -}}
            export SSH_KEY="{{ .Data.data.value }}"
          {{- end }}`}}
    spec:
      serviceAccountName: vault
      automountServiceAccountToken: true
      containers:
      - name: docker-build
        image: "docker:{{ .Values.docker.version }}"
        resources:
          requests:
            ephemeral-storage: "2Gi"
            cpu: "250m"
            memory: "0.5Gi"
          limits:
            ephemeral-storage: "2Gi"
            cpu: "250m"
            memory: "0.5Gi"
        command: ["sh", "-c"]
        args:
        - |
          source /vault/secrets/config &&
          mkdir -p ~/.ssh &&
          echo "$SSH_KEY" | base64 -d > ~/.ssh/id_rsa &&
          chmod 600 ~/.ssh/id_rsa &&
          eval $(ssh-agent -s) &&
          ssh-add ~/.ssh/id_rsa &&
          ssh-keyscan github.com >> ~/.ssh/known_hosts &&
          apk add --no-cache git &&
          git clone -b {{ .Values.application.branch }} {{ .Values.application.githubLink }} /app/breizhsport &&
          cd /app/breizhsport &&
          rm docker-compose.yml &&
          docker image prune -a -f &&
          docker system prune -a --volumes -f &&
          docker build -t breizhsport:production . &&
          echo "Build completed"
        volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
      restartPolicy: Never
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
          type: Socket
