apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cube-3-application-storage-pvc
  namespace: cube-3
  labels:
    app: application
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.application.storage }}
  selector:
    matchLabels:
      type: local
      app: application
  