apiVersion: v1
kind: Secret
metadata:
  name: application-secret
  namespace: cube-3
type: Opaque
data:
  SSH_KEY: {{ .Values.application.sshKey }}
  APP_KEY: {{ .Values.application.key | b64enc }}

  MAIL_USERNAME: {{ .Values.application.mail.username | b64enc }}
  MAIL_PASSWORD: {{ .Values.application.mail.password | b64enc }}
  MAIL_ENCRYPTION: {{ .Values.application.mail.encryption | b64enc }}
  MAIL_VERIFY_PEER: {{ .Values.application.mail.verifyPeer | b64enc }}
  MAIL_ALLOW_SELF_SIGNED: {{ .Values.application.mail.allowSelfSigned | b64enc }}