apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-application-external-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-application
  ports:
  - port: {{ .Values.application.port }}
    targetPort: {{ .Values.application.targetPort }}