apiVersion: v1
kind: ConfigMap
metadata:
  name: data-base-config-map
  namespace: cube-3
data:
  DB_HOST: "cube-3-data-base-internal-service"
  DB_DATABASE: "{{ .Values.dataBase.dbName }}"
  DB_PORT: "{{ .Values.dataBase.port | toString }}"
  DB_SEED: "{{ .Values.dataBase.seed }}"