apiVersion: v1
kind: ConfigMap
metadata:
  name: data-base-config-map
  namespace: cube-3
data:
  DB_HOST: "{{ .Values.dataBase.host }}"
  DB_DATABASE: "{{ .Values.dataBase.dbName }}"
  DB_PORT: "{{ .Values.dataBase.port | toString }}"
  DB_SEED: "{{ .Values.dataBase.seed }}"
  DB_HOST_AUTH_METHOD: "{{ .Values.dataBase.authMethod }}"