apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-base-deployment
  namespace: cube-3
spec:
  replicas: {{ .Values.dataBase.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-data-base
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-data-base
    spec:
      containers:
        - name: data-base
          image: {{ .Values.dataBase.version }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.dataBase.port }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: data-base-secret
                  key: DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: data-base-secret
                  key: DB_PASSWORD
          envFrom:
            - secretRef:
                name: data-base-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: cube-3-db-storage-pvc