apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-base-deployment
  namespace: cube-3
spec:
  replicas: {{ .Values.data-base.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-data-base
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-data-base
    spec:
      containers:
        - name: data-base
          image: "{ .Values.data-base.version }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.data-base.port }}
          envFrom:
            - secretRef:
                name: data-base-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: cube-3-storage-pvc