apiVersion: batch/v1
kind: Job
metadata:
  name: create-db-job
  namespace: argo-kube-test
spec:
  template:
    spec:
      containers:
      - name: create-db
        image: "postgres:{{ .Values.postgres.version }}"
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret 
              key: POSTGRES_PASSWORD
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Listing databases :"
            psql -h {{ .Release.Name }}-database-internal-service -U {{ .Values.postgres.user }} -p {{ .Values.postgres.port }} -d postgres -c "\l"

            DB_EXISTS=$(psql -h {{ .Release.Name }}-database-internal-service -U {{ .Values.postgres.user }} -p {{ .Values.postgres.port }} -d postgres -tAc "SELECT 1 FROM pg_database WHERE datname='{{ .Values.postgres.dbName }}'")
            if [ -z "$DB_EXISTS" ]; then
              echo "Creating '{{ .Values.postgres.dbName }}' database"
              psql -h {{ .Release.Name }}-database-internal-service -U {{ .Values.postgres.user }} -p {{ .Values.postgres.port }} -d postgres -c "CREATE DATABASE \"{{ .Values.postgres.dbName }}\""
            else
              echo "Database '{{ .Values.postgres.dbName }}' already exists."
              echo "Content of '{{ .Values.postgres.dbName }}' database :"
              psql -h {{ .Release.Name }}-database-internal-service -U {{ .Values.postgres.user }} -p {{ .Values.postgres.port }} -d {{ .Values.postgres.dbName }} -c "\dt"
            fi

        volumeMounts:
        - name: schema-volume
          mountPath: /schema
      restartPolicy: Never
      volumes:
      - name: schema-volume
  backoffLimit: 3
