apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cube-3-storage-pvc
  labels:
    app: data-base
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.data-base.storage }}
  