apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cube-3-storage-pvc
  labels:
    app: dataBase
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.dataBase.storage }}
  