apiVersion: v1
kind: PersistentVolume
metadata:
  name: cube-3-db-storage-pv
  namespace: cube-3
  labels:
    type: local
    app: database
spec:
  capacity:
    storage: {{ .Values.dataBase.storage }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/database/breizhsport
  