apiVersion: v1
kind: Secret
metadata:
  name: data-base-secret
  namespace: cube-3
type: Opaque
data:
  DB_USERNAME: {{ .Values.dataBase.username | b64enc }}
  DB_PASSWORD: {{ .Values.dataBase.password | b64enc }}