apiVersion: v1
kind: Secret
metadata:
  name: data-base-secret
  namespace: cube-3
type: Opaque
data:
  POSTGRES_DB: {{ .Values.data-base.dbName | b64enc }}
  POSTGRES_USER: {{ .Values.data-base.user | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.data-base.password | b64enc }}
  POSTGRES_PORT: {{ .Values.data-base.port | toString | b64enc }}