apiVersion: v1
kind: Secret
metadata:
  name: data-base-secret
  namespace: cube-3
type: Opaque
data:
  POSTGRES_DB: {{ .Values.dataBase.dbName | b64enc }}
  POSTGRES_USER: {{ .Values.dataBase.user | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.dataBase.password | b64enc }}
  POSTGRES_PORT: {{ .Values.dataBase.port | toString | b64enc }}