apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: argo-kube-test
type: Opaque
data:
  POSTGRES_DB: {{ .Values.postgres.dbName | b64enc }}
  POSTGRES_USER: {{ .Values.postgres.user | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc }}
  POSTGRES_PORT: {{ .Values.postgres.port | toString | b64enc }}