apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-data-base-internal-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-data-base
  ports:
    - name: internal-data-base-port
      port: {{ .Values.dataBase.port }}
      targetPort: {{ .Values.dataBase.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-data-base-external-service
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Release.Name }}-data-base
  ports:
    - name: external-data-base-port
      port: {{ .Values.dataBase.port }}
      targetPort: {{ .Values.dataBase.port }}