apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-database-internal-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-database
  ports:
    - name: internal-db-port
      port: {{ .Values.dataBase.port }}
      targetPort: {{ .Values.dataBase.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-database-external-service
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Release.Name }}-database
  ports:
    - name: external-db-port
      port: {{ .Values.dataBase.port }}
      targetPort: {{ .Values.dataBase.port }}