apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: laravel-ingress
  namespace: cube-3
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: {{ .Values.application.frontEndUrl }}
spec:
  ingressClassName: nginx
  rules:
    - host: breizhsport-prod.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-application-external-service
                port:
                  number: {{ .Values.ingress.port }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-application-external-service
                port:
                  number: {{ .Values.ingress.port }}
