apiVersion: v1
kind: Secret
metadata:
  name: ssh-secret
  namespace: cube-3
type: Opaque
data:
  SSH_PRIVATE_KEY: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNEVDZXQ1Z6NGVLSU4xSmJnMUFBTVVkM1pFZmtTNWFPMU1DRHVqemRvTmlLUUFBQUpoNzBYTTBlOUZ6Ck5BQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDRFQ2V0NWejRlS0lOMUpiZzFBQU1VZDNaRWZrUzVhTzFNQ0R1anpkb05pS1EKQUFBRURlUklJVlBRM0pCOStaMTduaXlTSTMwSG0ySzJ4MVhKQ2hzN1lBUTlrMFk5UHBZSlhQaDRvZzNVbHVEVUFBeFIzZAprUitSTGxvN1V3SU82UE4yZzJJcEFBQUFFV0Z5WjI5alpDMWhZMk5sYzNNdGEyVjVBUUlEQkE9PQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0=