apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontEnd-deployment
  namespace: cube-3
spec:
  replicas: {{ .Values.frontEnd.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontEnd
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-frontEnd
    spec:
      containers:
        - name: frontEnd-container
          image: "breizhsport-frontEnd:local"
          ports:
            - containerPort: {{ .Values.frontEnd.port }}
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"