apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-deployment
  namespace: cube-3
spec:
  replicas: {{ .Values.frontEnd.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-front-end
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-front-end
    spec:
      containers:
        - name: front-end-container
          image: "breizhsport-front-end:local"
          ports:
            - containerPort: {{ .Values.frontEnd.port }}
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"