apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-front-end-external-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-front-end
  ports:
    - protocol: TCP
      port: {{ .Values.front-end.port }}
      targetPort: {{ .Values.front-end.port }}