apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-end-deployment
  namespace: cube-3
spec:
  replicas: {{ .Values.back-end.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-back-end
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-back-end
    spec:
      containers:
        - name: back-end-container
          image: "breizhsport-server:local"
          ports:
            - containerPort: {{ .Values.back-end.port }}
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: data-base-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: data-base-secret
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: data-base-secret
                  key: POSTGRES_DB
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: data-base-secret
                  key: POSTGRES_PORT
            - name: DB_LOCATION
              value: "{{ .Release.Name }}-data-base-internal-service"
            - name: API_PORT
              valueFrom:
                secretKeyRef:
                  name: back-end-secret
                  key: API_PORT
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: back-end-secret
                  key: JWT_SECRET
            - name: API_EMAIL_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: back-end-secret
                  key: API_EMAIL_ADDRESS
            - name: API_EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: back-end-secret
                  key: API_EMAIL_PASSWORD
            - name: FRONTEND_URL
              valueFrom:
                secretKeyRef:
                  name: back-end-secret
                  key: FRONTEND_URL
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: back-end-secret
                  key: NODE_ENV