apiVersion: v1
kind: Secret
metadata:
  name: back-end-secret
  namespace: cube-3
type: Opaque
data:
  API_PORT: {{ .Values.backEnd.port | toString | b64enc }}
  NODE_ENV: {{ .Values.backEnd.env | b64enc }}
  JWT_SECRET: {{ .Values.backEnd.jwtSecret | b64enc }}
  API_EMAIL_ADDRESS: {{ .Values.backEnd.emailAddress | b64enc }}
  API_EMAIL_PASSWORD: {{ .Values.backEnd.emailPassword | b64enc }}
  FRONTEND_URL: {{ .Values.backEnd.frontEndUrl | b64enc }}
  SSH_KEY: {{ .Values.backEnd.sshKey }}