apiVersion: v1
kind: Secret
metadata:
  name: back-end-secret
  namespace: cube-3
type: Opaque
data:
  API_PORT: {{ .Values.back-end.port | toString | b64enc }}
  NODE_ENV: {{ .Values.back-end.env | b64enc }}
  JWT_SECRET: {{ .Values.back-end.jwtSecret | b64enc }}
  API_EMAIL_ADDRESS: {{ .Values.back-end.emailAddress | b64enc }}
  API_EMAIL_PASSWORD: {{ .Values.back-end.emailPassword | b64enc }}
  FRONTEND_URL: {{ .Values.back-end.frontEndUrl | b64enc }}