apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-back-end-external-service
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Release.Name }}-back-end
  ports:
  - port: {{ .Values.back-end.port }}
    targetPort: {{ .Values.back-end.port }}