apiVersion: batch/v1
kind: Job
metadata:
  name: build-breizhsport-api
  namespace: cube-3
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
      - name: docker-build
        image: docker:20.10.24-dind
        command: ["sh", "-c"]
        args:
        - |
          apk add --no-cache git &&
          git clone -b {{ .Values.api.branch }} {{ .Values.api.githubLink }} /app/breizhsport-server &&
          cd /app/breizhsport-server &&
          docker build -t breizhsport-server:local . &&
          echo "Build complete"
        volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
      restartPolicy: Never
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
          type: Socket