apiVersion: batch/v1
kind: Job
metadata:
  name: build-breizhsport-api
  namespace: cube-3
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
      - name: docker-build
        image: docker:20.10.24-dind
        command: ["sh", "-c"]
        args:
        - |
          # Installation des paquets nécessaires
          apk add --no-cache git openssh-client openssl &&
          
          # Création du répertoire SSH
          mkdir -p ~/.ssh &&
          
          # Débogage : afficher le contenu de la variable SSH_PRIVATE_KEY
          echo "Contenu de SSH_PRIVATE_KEY (début) :" &&
          echo "$SSH_PRIVATE_KEY" | cut -c1-50 &&
          
          # Décodage et sauvegarde de la clé
          echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa &&
          
          # Vérification des permissions et du contenu
          chmod 600 ~/.ssh/id_rsa &&
          ls -l ~/.ssh/id_rsa &&
          head -n 1 ~/.ssh/id_rsa &&
          
          # Tentative de conversion de la clé
          ssh-keygen -p -m PEM -f ~/.ssh/id_rsa -N '' 2>&1 ||
          
          # Si la conversion échoue, afficher plus de détails
          (echo "Erreur de conversion de clé" && cat ~/.ssh/id_rsa) &&
          
          # Test de la clé SSH
          ssh-keygen -y -f ~/.ssh/id_rsa &&
          
          # Ajout des hôtes connus
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts &&
          
          # Clonage du dépôt
          GIT_SSH_COMMAND="ssh -v" git clone -b {{ .Values.api.branch }} {{ .Values.api.githubLink }} /app/breizhsport-server &&
          
          # Construction de l'image
          cd /app/breizhsport-server &&
          docker build -t breizhsport-server:local . &&
          echo "Build complete"
        env:
          - name: SSH_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: ssh-secret
                key: SSH_PRIVATE_KEY
        volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
      restartPolicy: Never
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
          type: Socket