apiVersion: batch/v1
kind: Job
metadata:
  name: build-breizhsport-api
  namespace: cube-3
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
      - name: docker-build
        image: docker:20.10.24-dind
        command: ["sh", "-c"]
        args:
        - |
          # Installation des paquets nécessaires
          apk add --no-cache git openssh-client openssl &&
          
          # Création du répertoire SSH
          mkdir -p ~/.ssh &&
          
          # Débogage complet
          echo "Début du débogage SSH" &&
          echo "Contenu brut de SSH_PRIVATE_KEY :" &&
          echo "$SSH_PRIVATE_KEY" &&
          
          # Décodage correct
          echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa &&
          
          # Vérifications
          chmod 600 ~/.ssh/id_rsa &&
          ls -l ~/.ssh/id_rsa &&
          cat ~/.ssh/id_rsa &&
          
          # Vérification du format de la clé
          ssh-keygen -l -f ~/.ssh/id_rsa &&
          
          # Ajout des hôtes connus
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts &&
          
          # Test de connexion SSH
          ssh -T git@github.com || true &&
          
          # Clonage du dépôt
          GIT_SSH_COMMAND="ssh -vvv" git clone -b {{ .Values.api.branch }} {{ .Values.api.githubLink }} /app/breizhsport-server &&
          
          # Construction de l'image
          cd /app/breizhsport-server &&
          docker build -t breizhsport-server:local . &&
          echo "Build complete"
        env:
          - name: SSH_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: ssh-secret
                key: SSH_PRIVATE_KEY
        volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
      restartPolicy: Never
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
          type: Socket