apiVersion: batch/v1
kind: Job
metadata:
  name: build-breizhsport-api
  namespace: cube-3
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
      - name: docker-build
        image: docker:20.10.24-dind
        command: ["sh", "-c"]
        args:
        - |
          apk add --no-cache git openssh-client &&
          mkdir -p ~/.ssh &&
          echo "$SSH_PRIVATE_KEY" &&
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa &&
          chmod 600 ~/.ssh/id_rsa &&
          eval `ssh-agent -s` &&
          ssh-add ~/.ssh/id_rsa &&
          git clone -b {{ .Values.api.branch }} {{ .Values.api.githubLink }} /app/breizhsport-server &&
          cd /app/breizhsport-server &&
          #rm docker-compose.yaml &&
          docker build -t breizhsport-server:local . &&
          echo "Build complete"
        env:
          - name: SSH_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: ssh-secret
                key: SSH_PRIVATE_KEY
        volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
      restartPolicy: Never
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
          type: Socket