apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: cube-3
type: Opaque
data:
  API_PORT: {{ .Values.node.port | toString | b64enc }}
  NODE_ENV: {{ .Values.node.env | b64enc }}
  API_SECRET_KEY: {{ .Values.node.secretKey | b64enc }}